// clientConfig.js

export const clients = {
  alder: {
    heading: "Alder Construction's",
    background: "images/alder_image.jpg",
    logo: "images/alder_logo.png",
    altText: "Alder Construction Logo",
    preloadImage: true,
    basePath: "images/",
    brandColor: "#445777",
  },
  business_intuition: {
    heading: "Business Intuition's",
    background: "images/business_intuition_image.jpg",
    logo: "images/business_intuition_logo.svg",
    altText: "Business Intuition Logo",
    preloadImage: true,
    basePath: "images/",
    brandColor: "#F04E23",
  },
  cop: {
    heading: "COP Construction's",
    background: "images/cop_image.jpg",
    logo: "images/cop_logo.png",
    altText: "COP Construction Logo",
    preloadImage: true,
    basePath: "images/",
    brandColor: "#6C7C90",
  },
  havenlight: {
    heading: "Havenlight's",
    background: "images/havenlight_image.jpg",
    logo: "images/havenlight_logo.png",
    altText: "Havenlight Logo",
    preloadImage: true,
    basePath: "images/",
    brandColor: "#A9B7C6",
  },
  remedyww: {
    heading: "Remedy World Wide's",
    background: "images/remedyww_image.jpg",
    logo: "images/remedyww_logo.png",
    altText: "Remedy World Wide Logo",
    preloadImage: true,
    basePath: "images/",
    brandColor: "#A9B7C6",
  },
  skyline: {
    heading: "Skyline Electric's",
    background: "images/skyline_image.png",
    logo: "images/skyline_logo.png",
    altText: "Skyline Electric Logo",
    preloadImage: true,
    basePath: "images/",
    brandColor: "#FBBF24",
  },
  vlcm: {
    heading: "VLCM's",
    background: "images/vlcm_image.jpg",
    logo: "images/vlcm_logo.svg",
    altText: "VLCM Logo",
    preloadImage: true,
    basePath: "images/",
    brandColor: "#28A745",
  },
  winward: {
    heading: "Winward Electric's",
    background: "images/winward_image.jpg",
    logo: "images/winward_logo.png",
    altText: "Winward Electric Logo",
    preloadImage: true,
    basePath: "images/",
    brandColor: "#9C27B0",
  },

  // 🌐 Fallback configuration
  default: {
    heading: "ClarityBots",
    background: "images/default_background.jpg",
    logo: "images/default_logo.png",
    altText: "ClarityBots Default Logo",
    preloadImage: false,
    basePath: "images/",
    brandColor: "#FF7900",
  },
};
